import { createFileRoute, redirect } from "@tanstack/react-router";
import { useState } from "react";
import { Mail, Trash2, UserPlus, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ConfirmDialog, FieldError, Modal } from "@/components/ui/modal";
import { getUser } from "@/lib/auth";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { canAccessRoute, permissions } from "@/lib/roles";
export const Route=createFileRoute("/members")({ beforeLoad: () => { if (!canAccessRoute("/members")) throw redirect({ to: "/dashboard" }); }, component:MembersPage });
type Role="Admin"|"Member"|"Viewer"; type Member={id:number;name:string;email:string;role:Role;status:"Active"|"Invited"};
function MembersPage(){
 const current=getUser(); const [members,setMembers]=useState<Member[]>([{id:1,name:current?.name??"Lab Operator",email:current?.email??"operator@lab.local",role:"Admin",status:"Active"},{id:2,name:"Narin Chai",email:"narin@lab.local",role:"Member",status:"Active"},{id:3,name:"Maya Chen",email:"maya@lab.local",role:"Viewer",status:"Active"}]);
 const [inviteOpen,setInviteOpen]=useState(false);const [email,setEmail]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);const [removing,setRemoving]=useState<Member|null>(null);
 const invite=async(event:React.FormEvent)=>{event.preventDefault();const value=email.trim();if(!value){setError("Email address is required");return}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)){setError("Enter a valid email address");return}setLoading(true);await new Promise(resolve=>setTimeout(resolve,600));setLoading(false);setInviteOpen(false);setEmail("");toast.success("Invitation sent")};
 const remove=async()=>{if(!removing)return;setLoading(true);await new Promise(resolve=>setTimeout(resolve,400));setMembers(items=>items.filter(item=>item.id!==removing.id));setLoading(false);setRemoving(null);toast.success("Member removed")};
 return <AppShell title="Members" subtitle="People with access to the Lab Environment Monitor"><div className="mx-auto max-w-[1200px]"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Team Members</h2><p className="text-sm text-slate-500">{members.length} people currently have access</p></div>{permissions.canInviteUsers && <Button onClick={()=>{setError("");setInviteOpen(true)}} className="gap-2 bg-blue-600 hover:bg-blue-700"><UserPlus className="h-4 w-4"/>Invite User</Button>}</div><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Member</th><th className="px-5 py-3">Email</th><th className="px-5 py-3">Current role</th><th className="px-5 py-3">Status</th>{permissions.canRemoveMembers && <th className="px-5 py-3 text-right">Action</th>}</tr></thead><tbody className="divide-y">{members.map(member=><tr key={member.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-blue-100 font-bold text-blue-700">{member.name.charAt(0)}</div><span className="font-semibold">{member.name}</span></div></td><td className="px-5 py-4 text-slate-600">{member.email}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{member.role}</span></td><td className="px-5 py-4"><span className={cn("inline-flex items-center gap-1.5 text-xs font-semibold",member.status==="Active"?"text-emerald-700":"text-amber-700")}><span className={cn("h-1.5 w-1.5 rounded-full",member.status==="Active"?"bg-emerald-500":"bg-amber-500")}/>{member.status}</span></td>{permissions.canRemoveMembers && <td className="px-5 py-4 text-right"><Button variant="ghost" size="sm" onClick={()=>setRemoving(member)} className="gap-1.5 text-red-600 hover:bg-red-50 hover:text-red-700"><Trash2 className="h-3.5 w-3.5"/>Remove</Button></td>}</tr>)}</tbody></table></div></Card><div className="mt-4 flex items-start gap-3 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-800"><Users className="mt-0.5 h-4 w-4 shrink-0"/><p>Roles are displayed for reference only. Role assignment and permissions will be managed by backend policy in a future update.</p></div></div>
 <Modal open={inviteOpen} onClose={()=>!loading&&setInviteOpen(false)} title="Invite User" description="Send an invitation to access this monitoring environment"><form onSubmit={invite}><div className="px-5 py-5"><Label htmlFor="invite-email" className="mb-1.5 block">Email address</Label><div className="relative"><Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><Input id="invite-email" type="email" value={email} onChange={event=>{setEmail(event.target.value);setError("")}} placeholder="colleague@lab.com" className="pl-9"/></div><FieldError>{error}</FieldError><p className="mt-3 text-xs text-slate-500">The system will determine the member's role. No role is selected in this invitation.</p></div><div className="flex justify-end gap-2 border-t bg-slate-50 px-5 py-3"><Button type="button" variant="outline" onClick={()=>setInviteOpen(false)} disabled={loading}>Cancel</Button><Button type="submit" disabled={loading} className="bg-blue-600 hover:bg-blue-700">{loading?"Sending...":"Send Invite"}</Button></div></form></Modal>
 {permissions.canRemoveMembers && <ConfirmDialog open={!!removing} onClose={()=>setRemoving(null)} onConfirm={remove} title="Remove Member" description={`Are you sure you want to remove ${removing?.name??"this user"} from the system?`} confirmLabel="Remove" loading={loading}/>}
 </AppShell>;
}
