import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Droplets, MapPin, Pencil, Plus, Radio, Thermometer, Trash2 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ConfirmDialog, FieldError, Modal } from "@/components/ui/modal";
import { useLiveSensors, type Sensor } from "@/lib/sensors";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

export const Route=createFileRoute("/sensors")({component:SensorsPage});
type SensorRecord=Sensor&{minTemp:number;maxTemp:number;minHumidity:number;maxHumidity:number};
type FormState={name:string;sensorId:string;location:string;minTemp:string;maxTemp:string;minHumidity:string;maxHumidity:string};
type Errors=Partial<Record<keyof FormState,string>>;
const emptyForm:FormState={name:"",sensorId:"",location:"",minTemp:"18",maxTemp:"30",minHumidity:"35",maxHumidity:"65"};
const enrich=(sensor:Sensor):SensorRecord=>({...sensor,minTemp:18,maxTemp:30,minHumidity:35,maxHumidity:65});

function SensorsPage(){
 const liveSensors=useLiveSensors();
 const [records,setRecords]=useState<SensorRecord[]>(()=>liveSensors.map(enrich));
 const [editing,setEditing]=useState<SensorRecord|null>(null); const [form,setForm]=useState<FormState>(emptyForm); const [errors,setErrors]=useState<Errors>({}); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [deleting,setDeleting]=useState<SensorRecord|null>(null);
 useEffect(()=>setRecords(current=>current.map(record=>{const live=liveSensors.find(item=>item.id===record.id);return live?{...record,temperature:live.temperature,humidity:live.humidity,status:live.status}:record})),[liveSensors]);
 const update=(key:keyof FormState)=>(event:React.ChangeEvent<HTMLInputElement>)=>{setForm({...form,[key]:event.target.value});setErrors({...errors,[key]:undefined})};
 const showAdd=()=>{setEditing(null);setForm(emptyForm);setErrors({});setOpen(true)};
 const showEdit=(sensor:SensorRecord)=>{setEditing(sensor);setForm({name:sensor.name,sensorId:String(sensor.id),location:sensor.location,minTemp:String(sensor.minTemp),maxTemp:String(sensor.maxTemp),minHumidity:String(sensor.minHumidity),maxHumidity:String(sensor.maxHumidity)});setErrors({});setOpen(true)};
 const validate=()=>{const next:Errors={}; if(!form.name.trim())next.name="Sensor name is required";if(!form.sensorId.trim())next.sensorId="Sensor ID is required";else if(!/^\d+$/.test(form.sensorId))next.sensorId="Sensor ID must be a whole number";else if(records.some(record=>record.id===Number(form.sensorId)&&record.id!==editing?.id))next.sensorId="This Sensor ID already exists";if(!form.location.trim())next.location="Location is required";const numeric:[keyof FormState,string][]=[["minTemp","Minimum temperature"],["maxTemp","Maximum temperature"],["minHumidity","Minimum humidity"],["maxHumidity","Maximum humidity"]];numeric.forEach(([key,label])=>{if(form[key].trim()===""||!Number.isFinite(Number(form[key])))next[key]=label+" must be a valid number"});if(!next.minTemp&&!next.maxTemp&&Number(form.minTemp)>Number(form.maxTemp)){next.minTemp="Minimum temperature cannot exceed maximum";next.maxTemp="Maximum temperature must be at least the minimum"}if(!next.minHumidity&&!next.maxHumidity&&Number(form.minHumidity)>Number(form.maxHumidity)){next.minHumidity="Minimum humidity cannot exceed maximum";next.maxHumidity="Maximum humidity must be at least the minimum"}setErrors(next);return Object.keys(next).length===0};
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(!validate())return;setSaving(true);await new Promise(resolve=>setTimeout(resolve,500));const values={name:form.name.trim(),id:Number(form.sensorId),location:form.location.trim(),minTemp:Number(form.minTemp),maxTemp:Number(form.maxTemp),minHumidity:Number(form.minHumidity),maxHumidity:Number(form.maxHumidity)};if(editing)setRecords(items=>items.map(item=>item.id===editing.id?{...item,...values}:item));else setRecords(items=>[...items,{...values,temperature:0,humidity:0,status:"Offline",x:50,y:50}]);setSaving(false);setOpen(false);toast.success(editing?"Sensor updated":"Sensor added")};
 const remove=async()=>{if(!deleting)return;setSaving(true);await new Promise(resolve=>setTimeout(resolve,400));setRecords(items=>items.filter(item=>item.id!==deleting.id));setSaving(false);setDeleting(null);toast.success("Sensor deleted")};
 return <AppShell title="Sensors" subtitle="View and manage registered monitoring devices"><div className="mx-auto max-w-[1400px]"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Registered Sensors</h2><p className="text-sm text-slate-500">{records.length} sensors in this environment</p></div><Button onClick={showAdd} className="gap-2 bg-blue-600 hover:bg-blue-700"><Plus className="h-4 w-4"/>Add Sensor</Button></div><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Sensor</th><th className="px-4 py-3">ID</th><th className="px-4 py-3">Temperature</th><th className="px-4 py-3">Humidity</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Location</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{records.map((sensor,index)=><tr key={sensor.id} className="hover:bg-slate-50/70"><td className="px-4 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue-50 text-blue-600"><Radio className="h-4 w-4"/></span><span className="font-semibold">{sensor.name}</span></div></td><td className="px-4 py-4 font-mono text-slate-500">{String(sensor.id).padStart(3,"0")}</td><td className="px-4 py-4"><span className="flex items-center gap-1.5 font-medium"><Thermometer className="h-4 w-4 text-orange-500"/>{sensor.temperature.toFixed(1)} °C</span></td><td className="px-4 py-4"><span className="flex items-center gap-1.5 font-medium"><Droplets className="h-4 w-4 text-sky-500"/>{sensor.humidity.toFixed(0)} %RH</span></td><td className="px-4 py-4"><span className={cn("inline-flex items-center gap-1.5 rounded-full px-2 py-1 text-xs font-semibold",sensor.status==="Online"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500")}><span className={cn("h-1.5 w-1.5 rounded-full",sensor.status==="Online"?"bg-emerald-500":"bg-slate-400")}/>{sensor.status}</span></td><td className="px-4 py-4"><span className="flex items-center gap-1.5 text-slate-600"><MapPin className="h-4 w-4"/>{sensor.location}</span></td><td className="px-4 py-4"><div className="flex justify-end gap-1"><Button variant="ghost" size="sm" onClick={()=>showEdit(sensor)} className="gap-1.5"><Pencil className="h-3.5 w-3.5"/>Edit</Button><Button variant="ghost" size="sm" onClick={()=>setDeleting(sensor)} className="gap-1.5 text-red-600 hover:bg-red-50 hover:text-red-700"><Trash2 className="h-3.5 w-3.5"/>Delete</Button></div></td></tr>)}</tbody></table></div></Card></div>
 <Modal open={open} onClose={()=>!saving&&setOpen(false)} title={editing?"Edit Sensor":"Add Sensor"} description="Device details and monitoring thresholds"><form onSubmit={save}><div className="grid gap-4 px-5 py-5 sm:grid-cols-2"><FormField label="Sensor name" error={errors.name}><Input value={form.name} onChange={update("name")} placeholder="Sensor 7"/></FormField><FormField label="Sensor ID" error={errors.sensorId}><Input value={form.sensorId} onChange={update("sensorId")} placeholder="007"/></FormField><div className="sm:col-span-2"><FormField label="Location" error={errors.location}><Input value={form.location} onChange={update("location")} placeholder="North bench"/></FormField></div><FormField label="Minimum temperature (°C)" error={errors.minTemp}><Input type="number" step="0.1" value={form.minTemp} onChange={update("minTemp")}/></FormField><FormField label="Maximum temperature (°C)" error={errors.maxTemp}><Input type="number" step="0.1" value={form.maxTemp} onChange={update("maxTemp")}/></FormField><FormField label="Minimum humidity (%RH)" error={errors.minHumidity}><Input type="number" step="0.1" value={form.minHumidity} onChange={update("minHumidity")}/></FormField><FormField label="Maximum humidity (%RH)" error={errors.maxHumidity}><Input type="number" step="0.1" value={form.maxHumidity} onChange={update("maxHumidity")}/></FormField></div><div className="flex justify-end gap-2 border-t bg-slate-50 px-5 py-3"><Button type="button" variant="outline" onClick={()=>setOpen(false)} disabled={saving}>Cancel</Button><Button type="submit" disabled={saving} className="bg-blue-600 hover:bg-blue-700">{saving?"Saving...":editing?"Save Changes":"Save Sensor"}</Button></div></form></Modal>
 <ConfirmDialog open={!!deleting} onClose={()=>setDeleting(null)} onConfirm={remove} title="Delete Sensor" description={`Are you sure you want to delete ${deleting?.name ?? "this sensor"}? This frontend-only change lasts until the page is reloaded.`} loading={saving}/>
 </AppShell>;
}
function FormField({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <div><Label className="mb-1.5 block text-slate-700">{label}</Label>{children}<FieldError>{error}</FieldError></div>}
